#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    chainbarPot,    sensorPotentiometer)
#pragma config(Sensor, in3,    mogoPot,        sensorPotentiometer)
#pragma config(Sensor, in4,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in5,    mogoSense,      sensorLineFollower)
#pragma config(Sensor, in8,    pwrExpStatus,   sensorAnalog)
#pragma config(Sensor, dgtl1,  driveEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, stackDetect,    sensorSONAR_mm)
#pragma config(Motor,  port1,           mogo,          tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           backLeftChassis, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeftChassis, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           rChainbar,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lChainbar,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           frontRightChassis, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           backRightChassis, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          intake,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(DatalogSeries, 0, "lift", Motors, MotorPower, port5, 20)
#pragma config(DatalogSeries, 1, "ultra", Sensors, Sensor, dgtl11, 50)
#pragma config(DatalogSeries, 2, "liftPot", Sensors, Sensor, in4, 10)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "general.h"
#include "motion.h"
#include "lift.h"
#include "manipulators.h"
#include "chassis.h"
#include "auton.h"
#include "lcd.h"


int gyroScale = 139;
void pre_auton()
{

	bStopTasksBetweenModes = false;
	bDisplayCompetitionStatusOnLcd = false;

	PIDInit( distancePIDValues, 0.2, 0, 0, 0, 0, CHASSIS_DISTANCE_SENSOR, 150, 200, 200 );
	PIDInit( sDistancePIDValues, 1.3, 0, 0.2, 0, 0, CHASSIS_DISTANCE_SENSOR, 100, 20, 30 );
	PIDInit( gyroPIDValues, 0.6, 0, 0.05, 0, 0, gyro, 150, 30, 200 );
	PIDInit( mogoPIDValues, 1.0, 0, 0.05, 0, 0, mogoPot, 5, 40, 200 );
	PIDInit( liftPIDValues, -0.2, 0, -0.02, 0, 0, LIFT_SENSOR, 150, 200, 250 );
	PIDInit( chainbarPIDValues, 0.2, 0, 0.01, 0, 0, chainbarPot, 50, 100, 300 );

	SensorType[ gyro ] = sensorNone;
	wait1Msec(1000);
	SensorType[ gyro ] = sensorGyro;
	wait1Msec(1100);

	SensorScale[gyro] = gyroScale;

	SensorValue[ driveEncoder ] = 0;

}

task autonomous()
{



}

float time;

task autonTask
{

	blueFiveRightStat();

}

task usercontrol()
{

	startTask( PIDLoop );

	while( true )
	{

		while( !vexRT[ Btn8D ] )
			wait1Msec( 20 );

		while( vexRT[ Btn8D ] )
			wait1Msec( 20 );

		float startTime = nPgmTime;

		clearTimer(T1);

		startTask( autonTask );

		while( time1[T1] < 15000 && !vexRT[ Btn8D ] )
			wait1Msec( 20 );

		stopTask( autonTask );

		time = nPgmTime - startTime;

		liftPIDEnabled = false;
		chainbarPIDEnabled = false;
		chassisPIDEnabled = false;
		mogoPIDEnabled = false;
		distancePIDEnabled = false;
		turnPIDEnabled = false;

		setChassis(0,0);
		setLift(0);
		setChainbar(0);
		setMogo(0);

		wait1Msec( 200 );

		//while( !vexRT[ Btn8D ] )
		//	wait1Msec( 20 );

		//clearTimer(T1);

	 // while ( time10[T1] < 10500 )
	 // {

	 // 	driverLift(  );
	 // 	setChassis( deadzone( vexRT[ Ch3 ], 10 ), deadzone( vexRT[ Ch2 ], 10 ) );

		//  updateAllBtnToggle();

	 // 	wait1Msec( 20 );

	 // }

	  setChassis(0,0);
		setLift(0);
		setChainbar(0);
		setMogo(0);

	}

}
